# COPIA questo file in secret.yaml e cambia le password
# Il file secret.yaml è escluso da git (.gitignore)
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: gestionale
type: Opaque
stringData:
  POSTGRES_DB: gestionale
  POSTGRES_USER: gestionale
  POSTGRES_PASSWORD: CAMBIA_QUESTA_PASSWORD
